// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS_SYSTEM_MVC.Data;

#nullable disable

namespace POS_SYSTEM_MVC.Migrations
{
    [DbContext(typeof(POSContext))]
    [Migration("20260506035216_add-migration v1")]
    partial class addmigrationv1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<decimal>("Salary")
                        .HasColumnType("smallmoney");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Casio"
                        });
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Footwear"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SaleTotalThreshold")
                        .HasColumnType("smallmoney");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ProductVariantId = 1,
                            Type = "Percentage",
                            Value = 10m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            ProductVariantId = 4,
                            Type = "Fixed",
                            Value = 5m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SaleTotalThreshold = 200m,
                            Type = "Percentage",
                            Value = 15m
                        });
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("smallmoney");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 120.00m,
                            BrandId = 1,
                            Name = "Air Max 90",
                            SubCategoryId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 90.00m,
                            BrandId = 2,
                            Name = "Stan Smith",
                            SubCategoryId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 25.00m,
                            BrandId = 2,
                            Name = "Classic Tee",
                            SubCategoryId = 3,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 75.00m,
                            BrandId = 3,
                            Name = "G-Shock DW",
                            SubCategoryId = 5,
                            UnitId = 1
                        });
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ProductAttributes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Color"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Size"
                        });
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.ProductAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("SubCategoryId", "AttributeId", "Value")
                        .IsUnique();

                    b.ToTable("ProductAttributeValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttributeId = 1,
                            SubCategoryId = 1,
                            Value = "Red"
                        },
                        new
                        {
                            Id = 2,
                            AttributeId = 1,
                            SubCategoryId = 1,
                            Value = "Blue"
                        },
                        new
                        {
                            Id = 3,
                            AttributeId = 1,
                            SubCategoryId = 1,
                            Value = "Black"
                        },
                        new
                        {
                            Id = 4,
                            AttributeId = 2,
                            SubCategoryId = 1,
                            Value = "40"
                        },
                        new
                        {
                            Id = 5,
                            AttributeId = 2,
                            SubCategoryId = 1,
                            Value = "41"
                        },
                        new
                        {
                            Id = 6,
                            AttributeId = 2,
                            SubCategoryId = 1,
                            Value = "42"
                        },
                        new
                        {
                            Id = 7,
                            AttributeId = 2,
                            SubCategoryId = 1,
                            Value = "43"
                        },
                        new
                        {
                            Id = 8,
                            AttributeId = 1,
                            SubCategoryId = 3,
                            Value = "White"
                        },
                        new
                        {
                            Id = 9,
                            AttributeId = 1,
                            SubCategoryId = 3,
                            Value = "Black"
                        },
                        new
                        {
                            Id = 10,
                            AttributeId = 1,
                            SubCategoryId = 3,
                            Value = "Gray"
                        },
                        new
                        {
                            Id = 11,
                            AttributeId = 2,
                            SubCategoryId = 3,
                            Value = "S"
                        },
                        new
                        {
                            Id = 12,
                            AttributeId = 2,
                            SubCategoryId = 3,
                            Value = "M"
                        },
                        new
                        {
                            Id = 13,
                            AttributeId = 2,
                            SubCategoryId = 3,
                            Value = "L"
                        },
                        new
                        {
                            Id = 14,
                            AttributeId = 2,
                            SubCategoryId = 3,
                            Value = "XL"
                        },
                        new
                        {
                            Id = 15,
                            AttributeId = 1,
                            SubCategoryId = 5,
                            Value = "Silver"
                        },
                        new
                        {
                            Id = 16,
                            AttributeId = 1,
                            SubCategoryId = 5,
                            Value = "Gold"
                        },
                        new
                        {
                            Id = 17,
                            AttributeId = 1,
                            SubCategoryId = 5,
                            Value = "Black"
                        });
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("smallmoney");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            SKU = "AM90-RED-41",
                            StockQuantity = 10,
                            UnitPrice = 130.00m
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            SKU = "AM90-RED-42",
                            StockQuantity = 8,
                            UnitPrice = 130.00m
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 1,
                            SKU = "AM90-BLU-41",
                            StockQuantity = 5,
                            UnitPrice = 130.00m
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 3,
                            SKU = "TEE-WHT-M",
                            StockQuantity = 20,
                            UnitPrice = 28.00m
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            SKU = "TEE-BLK-L",
                            StockQuantity = 15,
                            UnitPrice = 28.00m
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 4,
                            SKU = "GSH-BLK",
                            StockQuantity = 7,
                            UnitPrice = 80.00m
                        });
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CashierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("smallmoney");

                    b.Property<string>("DiscountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.SaleLine", b =>
                {
                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("smallmoney");

                    b.Property<string>("DiscountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("OriginalUnitPrice")
                        .HasColumnType("smallmoney");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("SaleId", "ProductVariantId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("SaleLines");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Sneakers"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Sandals"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Jackets"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Watches"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Bags"
                        });
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.SubCategoryAttribute", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.HasKey("SubCategoryId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("SubCategoryAttributes");

                    b.HasData(
                        new
                        {
                            SubCategoryId = 1,
                            AttributeId = 1
                        },
                        new
                        {
                            SubCategoryId = 1,
                            AttributeId = 2
                        },
                        new
                        {
                            SubCategoryId = 2,
                            AttributeId = 1
                        },
                        new
                        {
                            SubCategoryId = 2,
                            AttributeId = 2
                        },
                        new
                        {
                            SubCategoryId = 3,
                            AttributeId = 1
                        },
                        new
                        {
                            SubCategoryId = 3,
                            AttributeId = 2
                        },
                        new
                        {
                            SubCategoryId = 4,
                            AttributeId = 1
                        },
                        new
                        {
                            SubCategoryId = 4,
                            AttributeId = 2
                        },
                        new
                        {
                            SubCategoryId = 5,
                            AttributeId = 1
                        },
                        new
                        {
                            SubCategoryId = 6,
                            AttributeId = 1
                        });
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Piece"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pair"
                        });
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.VariantAttribute", b =>
                {
                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeValueId")
                        .HasColumnType("int");

                    b.HasKey("ProductVariantId", "AttributeValueId");

                    b.HasIndex("AttributeValueId");

                    b.ToTable("VariantAttributes");

                    b.HasData(
                        new
                        {
                            ProductVariantId = 1,
                            AttributeValueId = 1
                        },
                        new
                        {
                            ProductVariantId = 1,
                            AttributeValueId = 5
                        },
                        new
                        {
                            ProductVariantId = 2,
                            AttributeValueId = 1
                        },
                        new
                        {
                            ProductVariantId = 2,
                            AttributeValueId = 6
                        },
                        new
                        {
                            ProductVariantId = 3,
                            AttributeValueId = 2
                        },
                        new
                        {
                            ProductVariantId = 3,
                            AttributeValueId = 5
                        },
                        new
                        {
                            ProductVariantId = 4,
                            AttributeValueId = 8
                        },
                        new
                        {
                            ProductVariantId = 4,
                            AttributeValueId = 12
                        },
                        new
                        {
                            ProductVariantId = 5,
                            AttributeValueId = 9
                        },
                        new
                        {
                            ProductVariantId = 5,
                            AttributeValueId = 13
                        },
                        new
                        {
                            ProductVariantId = 6,
                            AttributeValueId = 17
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("POS_SYSTEM_MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("POS_SYSTEM_MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS_SYSTEM_MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("POS_SYSTEM_MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Discount", b =>
                {
                    b.HasOne("POS_SYSTEM_MVC.Models.Product", "Product")
                        .WithMany("Discounts")
                        .HasForeignKey("ProductId");

                    b.HasOne("POS_SYSTEM_MVC.Models.ProductVariant", "ProductVariant")
                        .WithMany("Discounts")
                        .HasForeignKey("ProductVariantId");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Product", b =>
                {
                    b.HasOne("POS_SYSTEM_MVC.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS_SYSTEM_MVC.Models.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS_SYSTEM_MVC.Models.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("SubCategory");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.ProductAttributeValue", b =>
                {
                    b.HasOne("POS_SYSTEM_MVC.Models.ProductAttribute", "Attribute")
                        .WithMany("Values")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS_SYSTEM_MVC.Models.SubCategory", "SubCategory")
                        .WithMany("AttributeValues")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.ProductVariant", b =>
                {
                    b.HasOne("POS_SYSTEM_MVC.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Sale", b =>
                {
                    b.HasOne("POS_SYSTEM_MVC.Models.ApplicationUser", "Cashier")
                        .WithMany("Sales")
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cashier");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.SaleLine", b =>
                {
                    b.HasOne("POS_SYSTEM_MVC.Models.ProductVariant", "ProductVariant")
                        .WithMany("SaleLines")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POS_SYSTEM_MVC.Models.Sale", "Sale")
                        .WithMany("SaleLines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.SubCategory", b =>
                {
                    b.HasOne("POS_SYSTEM_MVC.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.SubCategoryAttribute", b =>
                {
                    b.HasOne("POS_SYSTEM_MVC.Models.ProductAttribute", "Attribute")
                        .WithMany("SubCategoryAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POS_SYSTEM_MVC.Models.SubCategory", "SubCategory")
                        .WithMany("SubCategoryAttributes")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.VariantAttribute", b =>
                {
                    b.HasOne("POS_SYSTEM_MVC.Models.ProductAttributeValue", "AttributeValue")
                        .WithMany("VariantAttributes")
                        .HasForeignKey("AttributeValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POS_SYSTEM_MVC.Models.ProductVariant", "ProductVariant")
                        .WithMany("VariantAttributes")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttributeValue");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.ApplicationUser", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Product", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.ProductAttribute", b =>
                {
                    b.Navigation("SubCategoryAttributes");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.ProductAttributeValue", b =>
                {
                    b.Navigation("VariantAttributes");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.ProductVariant", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("SaleLines");

                    b.Navigation("VariantAttributes");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Sale", b =>
                {
                    b.Navigation("SaleLines");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.SubCategory", b =>
                {
                    b.Navigation("AttributeValues");

                    b.Navigation("Products");

                    b.Navigation("SubCategoryAttributes");
                });

            modelBuilder.Entity("POS_SYSTEM_MVC.Models.Unit", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
